// Generated by `wrangler types` — committed as a placeholder until the first run.
// Run `pnpm --filter @totvibe/web wrangler:types` to refresh after wrangler.jsonc changes.

interface Env {
  USER_DO: DurableObjectNamespace;
  PUBLIC_BASE: string;
  S3_ENDPOINT: string;
  S3_REGION: string;
  S3_BUCKET: string;
  S3_ACCESS_KEY_ID: string;
  S3_SECRET_ACCESS_KEY: string;
  PIPELINE_BASE: string;
  CALLBACK_HMAC_SECRET: string;
  CALLBACK_HMAC_SECRET_PREVIOUS?: string;
  RECONCILE_TIMEOUT_SECONDS: string;
}
